# Generated by Django 5.2.10 on 2026-01-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_body_post_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True, help_text='Raw HTML body (e.g. <h2>, <p>).'),
        ),
    ]
